version: '3.4'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server_container
    environment:
      SA_PASSWORD: Temporal1
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - my_network   

  pharmacyapi:
    image: pharmacyapi
    build:
     context: .
     dockerfile: PharmacyAPI/Dockerfile
    logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: 100m
    ports:
      - 8080:8080
    networks:
      - my_network
    depends_on:
      - sql_server     

  ejecutar_script:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sql_server
    command: /bin/bash -c "sleep 10 && /opt/mssql-tools/bin/sqlcmd -S sql_server -U sa -P Temporal1 -d master -i /scripts/create-database.sql"
    volumes:
      - ./sql-scripts:/scripts
    networks:
      - my_network
  tests: 
    image: functional-tests
    build:
      context: .
      dockerfile: tests/Dockerfile
    entrypoint: newman
    command: run APITest.postman_collection.json  --environment=testapi-enviroment.postman_environment.json --env-var="BaseUrl=http://pharmacyapi:8080" --reporters cli,json,junit --reporter-junit-export /data/results/TEST-Integration-Report.xml  --reporter-json-export /data/results/outputfile.json
    volumes:
      - ./results:/data/results
    depends_on:
      - pharmacyapi
      - sql_server
    networks:
      - my_network
networks:
  my_network:

