USE PharmacyDB;
GO

CREATE TABLE PharmacyDB.dbo.PharmacyDB(
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	
	PharmacyName [nvarchar](100) NOT NULL,
	Address [nvarchar](200) NOT NULL,
	[Notes] [text] NULL,
	
	Latitude float not NULL,
	Longitude float Not NULL
 CONSTRAINT [PK_Log_3] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] 

GO